export const fields = [
  { id: 1, name: 'RIO VERDE (GO)' },
  { id: 2, name: 'ACREÚNA (GO)' },
  { id: 3, name: 'ANAPOLIS (GO) - ALPHA' },
  { id: 4, name: 'BOM JESUS DE GOIÁS (GO)' },
  { id: 5, name: 'CAÇU (GO)' },
  { id: 6, name: 'CATALÃO (GO)' },
  { id: 7, name: 'GOIANÉSIA (GO)' },
  { id: 8, name: 'GOIÂNIA (GO) - JARDIM AMERICA' },
  { id: 9, name: 'GOIÂNIA (GO) - IEADVA' },
  { id: 11, name: 'ITUMBIARA (GO)' },
  { id: 12, name: 'JATAÍ (GO)' },
  { id: 13, name: 'JUSSARA (GO)' },
  { id: 14, name: 'MINEIROS (GO)' },
  { id: 15, name: 'MORRINHOS (GO)' },
  { id: 16, name: 'GOIANIA - GO - JARDIM PRESIDENTE' },
  { id: 17, name: 'QUIRINÓPOLIS (GO)' },
  { id: 18, name: 'SANTA FÉ DE GOIÁS (GO)' },
  { id: 19, name: 'SANTA HELENA (GO)' },
  { id: 20, name: 'SANTA RITA DO ARAGUAIA (GO)' },
  { id: 21, name: 'SERRANÓPOLIS (GO)' },
  { id: 22, name: 'CHAPADÃO DO CÉU (GO)' },
  { id: 23, name: 'BRASILIA (DF)' },
  { id: 24, name: 'GUAPÓ (GO)' },
  { id: 25, name: 'GOIÂNIA (GO) - MOVER DO ESPIRITO' },
  { id: 26, name: 'ANAPOLIS (GO) - GABRIEL' },
  { id: 28, name: 'APARECIDA DE GOIÂNIA (GO) - NOVA DE PAZ' },
  { id: 29, name: 'GOIÂNIA (GO) - CRIMEIA OESTE' },
  { id: 30, name: 'PIRACANJUBA (GO)' },
  { id: 31, name: 'JARAGUA (GO)' },
  { id: 32, name: 'SÃO SIMÃO (GO)' },
  { id: 33, name: 'ITAJA (GO)' },
  { id: 34, name: 'MONTES CLAROS DE GOIAS (GO)' },
  { id: 36, name: 'PEROLANDIA (GO)' },
  { id: 38, name: 'CERES (GO)' },
  { id: 39, name: 'GOIÂNIA (GO) - VALE DOS SONHOS' },
  { id: 40, name: 'GOIÂNIA (GO) - VIDA NOVA' },
  { id: 41, name: 'RIBEIRAOZINHO' },
  { id: 42, name: 'PORTELANDIA (GO)' },
  { id: 43, name: 'CACHOEIRA ALTA (GO)' },
  { id: 44, name: 'ARAGOIANIA (GO)' },
  { id: 45, name: 'MOZARLANDIA (GO)' },
  { id: 46, name: 'CACHOEIRA DOURADA' },
]
