import '@/styles/globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ptBR } from '@clerk/localizations'
import Providers from '@/components/providers'
import React from 'react'
import { fontSans } from '@/lib/fonts'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-BR" suppressHydrationWarning>
        <body className={fontSans.variable}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
