name: 'Code check'

on:
  pull_request:
    branches: ['*']

env:
  NEXT_PUBLIC_APP_URL: 'https://fake.com'
  DATABASE_URL: 'fake'
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'fake'
  CLERK_SECRET_KEY: 'fake'
  RESEND_API_KEY: 'fake'
  EMAIL_FROM_ADDRESS: 'fake@email.com'
  STRIPE_API_KEY: 'fake'
  STRIPE_WEBHOOK_SECRET: 'fake'
  STRIPE_TICKET_PRICE_ID: 'fake'

jobs:
  typecheck-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 'Setup Node 18'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck
